name: haathbarhao_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Rendering
  flutter_svg:
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.1
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod:

  # Navigation
  go_router: ^12.1.3

  # Network and Data
  dio: ^5.0.2
  http:

  # Authentication
  firebase_auth:
  google_sign_in: ^6.2.1
  sign_in_with_apple:

  # Notifications and Messaging
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^16.2.0

  # Storage
  shared_preferences:

  # Analytics and Crash Reporting
  firebase_analytics: ^10.8.0
  firebase_core: ^2.4.0
  firebase_performance: ^0.9.0+14
  firebase_crashlytics: ^3.0.15

  # Third-party Integrations
  image_picker: ^1.0.1
  url_launcher: ^6.1.14
  permission_handler: ^11.1.0

  # Utility and Miscellaneous
  intl:
  cupertino_icons: ^1.0.2
  flutter_timezone: ^1.0.7
  timezone: ^0.9.2
  html: ^0.15.4
  fluttertoast:
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.1
  flutter_launcher_icons:

flutter_gen:
  integration:
    flutter_svg:

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/