name: haathbarhao_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Rendering
  flutter_svg:
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.1
  google_fonts: ^6.1.0
  dropdown_button2: ^2.3.9

  # State Management
  flutter_riverpod:

  # Navigation
  go_router: ^12.1.3

  # Network and Data
  dio: ^5.0.2
  http:

  # Notifications and Messaging
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2

  # Storage
  shared_preferences: ^2.2.2

  # Analytics and Crash Reporting
  firebase_analytics: ^10.8.0
  firebase_core: ^2.32.0
  firebase_performance: ^0.9.0+14
  firebase_crashlytics: ^3.0.15
  firebase_storage: ^11.6.10

  # Third-party Integrations
  image_picker: ^1.0.1
  url_launcher: ^6.1.14
  permission_handler: ^11.1.0
  geocoding: ^2.0.4
  geolocator: ^9.0.0

  # Utility and Miscellaneous
  intl:
  cupertino_icons: ^1.0.2
  flutter_timezone: ^1.0.7
  timezone: ^0.9.2
  html: ^0.15.4
  fluttertoast:
  flutter_slidable: ^3.0.1
  loggy: ^2.0.3
  flutter_email_sender: ^6.0.1
  firebase_auth: ^4.20.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.1
  flutter_launcher_icons:

flutter_gen:
  integration:
    flutter_svg:

  colors:
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icons/

  fonts:
  - family: ClashDisplay
    fonts:
      - asset: assets/fonts/clash_display/ClashDisplay-Bold.otf
        weight: 700
        style: normal
      - asset: assets/fonts/clash_display/ClashDisplay-Extralight.otf
        weight: 200
        style: normal
      - asset: assets/fonts/clash_display/ClashDisplay-Light.otf
        weight: 300
        style: normal
      - asset: assets/fonts/clash_display/ClashDisplay-Medium.otf
        weight: 500
        style: normal
      - asset: assets/fonts/clash_display/ClashDisplay-Regular.otf
        weight: 400
        style: normal
      - asset: assets/fonts/clash_display/ClashDisplay-Semibold.otf
        weight: 600
        style: normal
